### ISSUE TITLE
Help text is misleading and other usage notes

### ISSUE THREAD

**Issue by chennin** [Osiris1975/namelist-mod-gen#11]
When trying to use the generator, I like to read the help text .. or at least part of it.

(Line breaks in these pastes may be spuriously added here when copying from my terminal)

```
$ ./src/namelist_mod_gen/namelist_mod_gen.py -h
usage: namelist_generator.py -c [NAMELIST_FILE]

A tool for creating Stellaris namelist mods from a CSV file

options:
  -h, --help            show this help message and exit
  -c NAMELISTS, --namelists NAMELISTS
                        path to the directory with namelist csv files (default: None)
  -a AUTHOR, --author AUTHOR
                        mod author (default: None)
  -m MOD_NAME, --mod_name MOD_NAME
                        name to use for the generated mod (default: None)
  -d DUMP_CSV_TEMPLATE, --dump_csv_template DUMP_CSV_TEMPLATE
                        dump a blank csv with namelist headers with the specified name (default: None)
```

Ok, I read the first line, let's try:

```
$ ./src/namelist_mod_gen/namelist_mod_gen.py -c examples/input_csvs/osiris_namelists/Osiris\ Namelists\ for\ Stellaris\ -\ American
.csv -a foo -m bar
$
```

Nothing? Ok, let's read the rest of the help, oh it takes a directory.

```
$ ./src/namelist_mod_gen/namelist_mod_gen.py -c examples/input_csvs/osiris_namelists/
Traceback (most recent call last):
  File "/mnt/c/Users/Chris/Documents/repos/namelist-mod-gen/./src/namelist_mod_gen/namelist_mod_gen.py", line 154, in <module>
    sys.exit(main())
  File "/mnt/c/Users/Chris/Documents/repos/namelist-mod-gen/./src/namelist_mod_gen/namelist_mod_gen.py", line 140, in main
    create_mod(args)
  File "/mnt/c/Users/Chris/Documents/repos/namelist-mod-gen/./src/namelist_mod_gen/namelist_mod_gen.py", line 43, in create_mod
    mod_dirs = make_mod_directories(args.mod_name)
  File "/mnt/c/Users/Chris/Documents/repos/namelist-mod-gen/./src/namelist_mod_gen/namelist_mod_gen.py", line 22, in make_mod_directories
    "namelist": os.path.join(c.MOD_OUTPUT_DIR, mod_name, 'common', 'name_lists'),
  File "/usr/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

Seems mod name is required. Similarly, so is author name.

```
$ ./src/namelist_mod_gen/namelist_mod_gen.py -c examples/input_csvs/osiris_namelists/ -m foo
Traceback (most recent call last):
  File "/mnt/c/Users/Chris/Documents/repos/namelist-mod-gen/./src/namelist_mod_gen/namelist_mod_gen.py", line 154, in <module>
    sys.exit(main())
  File "/mnt/c/Users/Chris/Documents/repos/namelist-mod-gen/./src/namelist_mod_gen/namelist_mod_gen.py", line 140, in main
    create_mod(args)
  File "/mnt/c/Users/Chris/Documents/repos/namelist-mod-gen/./src/namelist_mod_gen/namelist_mod_gen.py", line 50, in create_mod
    nl_dict, ord_dict = csv_to_dicts(f, args.author.lower())
AttributeError: 'NoneType' object has no attribute 'lower'

```

Next, let's "accidentally" give it the wrong dir:

```
$ ./src/namelist_mod_gen/namelist_mod_gen.py -c /tmp/empty -a foo -m bar
$
```

Also no output.

So I see several places for usability improvements:

1. NAMELIST_FILE should be NAMELIST_DIRECTORY in the top usage text
2. Author and mod name requirement should be enforced with a friendly message of some sort instead of an exception
3. It would be great if it printed the input files it found
4. And had some indication if 0 files were found
5. Input files should perhaps be limited to `*.csv`

I made these changes in https://github.com/chennin/namelist-mod-gen/commit/e40cef88d1d794d84ee2be382e5079a624e74c41 , in which I also added defaults for author and mod name, which I could be argued out of. I can open a PR or you can take the code you like, if you like.

Thank you!

**Comment by Osiris1975** [comment]
@chennin thanks, yes please open a PR. I appreciate your contribution! You're the first to take an interest so I haven't worried too much about documentation.
