### ISSUE TITLE
HEX missing from ordinal list

### ISSUE THREAD

**Issue by chennin** [Osiris1975/namelist-mod-gen#14]
Trying to use `$HEX$ Rust Soldiers` as an army name causes the following exception:

```
$ ../namelist-mod-gen/src/namelist_mod_gen/namelist_mod_gen.py -a forbiddenlake -m "Lemonade Names" -c input/
Found file "lemonade_input.csv"
Traceback (most recent call last):
  File "/mnt/c/Users/Chris/Documents/repos/stellaris-lemonade-names/../namelist-mod-gen/src/namelist_mod_gen/namelist_mod_gen.py", line 157, in <module>
    sys.exit(main())
  File "/mnt/c/Users/Chris/Documents/repos/stellaris-lemonade-names/../namelist-mod-gen/src/namelist_mod_gen/namelist_mod_gen.py", line 143, in main
    create_mod(args)
  File "/mnt/c/Users/Chris/Documents/repos/stellaris-lemonade-names/../namelist-mod-gen/src/namelist_mod_gen/namelist_mod_gen.py", line 49, in create_mod
    nl_dict, ord_dict = csv_to_dicts(f, args.author.lower())
  File "/mnt/c/Users/Chris/Documents/repos/stellaris-lemonade-names/../namelist-mod-gen/src/namelist_mod_gen/namelist_mod_gen.py", line 104, in csv_to_dicts
    seq_key = create_seq_key(k, v, author, namelist_dict['namelist_id'][0])
  File "/mnt/c/Users/Chris/Documents/repos/stellaris-lemonade-names/../namelist-mod-gen/src/namelist_mod_gen/namelist_mod_gen.py", line 87, in create_seq_key
    return f"{author.upper()}_{id.upper()}_{ord_base}_{c.ORD_TYPES[ord]}"
KeyError: 'HEX'
```

Simply adding `    "HEX": "HEX",` to `ORD_TYPES` in `src/namelist_mod_gen/constants.py` fixes the issue

![image](https://user-images.githubusercontent.com/2653277/225995077-16887cd2-5e44-4d7c-8204-9504b293146b.png)

If you check out the vanilla file `localisation/english/name_system_l_english.yml` under "SEQUENTIAL NAMES" you'll see several more you may want to add support for

Thank you!

**Comment by Osiris1975** [comment]
Updated to support HEX, CC, and CCC.
