### ISSUE TITLE
ModuleNotFoundError: No module named 'googletrans'

### ISSUE THREAD

**Issue by herbmaster** [Osiris1975/namelist-mod-gen#21]
**Describe the bug**

Following the instruction on windows and in an Ubuntu WSL, the script won't start with

```
$ poetry.exe run python src/namelist_mod_gen/namelist_mod_gen.py --help
Traceback (most recent call last):
  File "D:\Modding\stellaris\namelist-mod-gen\src\namelist_mod_gen\namelist_mod_gen.py", line 22, in <module>
    from translation.translation import translate_dict, translate
  File "D:\Modding\stellaris\namelist-mod-gen\src\namelist_mod_gen\translation\translation.py", line 13, in <module>
    import googletrans
ModuleNotFoundError: No module named 'googletrans'
```

**Expected behavior**
The usage message should have been printed.

**Comment by Osiris1975** [comment]
Thanks for your report. I need to update the project toml file.

**Comment by Osiris1975** [comment]
@herbmaster this should be fixed now. LMK if you have any more problems.
